---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: coachlight-k3s-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: >
    Application workloads for the Coachlight k3s homelab cluster. Owns
    user-facing applications and services deployed on the cluster.

  sourceRepos:
    - "*"

  # Applications should live in apps-* namespaces, e.g.:
  # apps-homepage, apps-paperless-ngx, apps-crafty-controller, etc.
  destinations:
    - server: https://kubernetes.default.svc
      namespace: apps-*

  orphanedResources:
    warn: true

  # Apps may need CRDs or ClusterRoles for operators
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
