- name: Extract ID from /etc/os-release
  set_fact:
    os_id: "{{ lookup('file', '/etc/os-release') | regex_search('^ID=([^\\n]+)', '\\1', multiline=True) }}"
  when: ansible_facts['os_family'] == 'RedHat'

- name: Set immutable fact
  set_fact:
    immutable: "{{ os_id[0] == 'aurora' }}"
  when: os_id is defined

- name: Include tasks for standard distros
  include_tasks: standard-distros.yml
  when: not immutable
