- name: Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: omz

- name: Install oh-my-zsh
  when: not omz.stat.exists
  block:
    - name: Download oh-my-zsh installer script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/omz_install.sh
        mode: "0755"

    - name: Run oh-my-zsh installer
      ansible.builtin.command: /bin/zsh /tmp/omz_install.sh --unattended
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

    - name: Set ZSH_THEME to "agnoster" in .zshrc
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        regexp: "^ZSH_THEME="
        line: 'ZSH_THEME="agnoster"'
