- name: Install productivity packages
  ansible.builtin.dnf:
    name:
      - inkscape
      - steam
      - musescore
      - krita
      - libreoffice
      - kdenlive
      - tailscale
    state: present
  become: true

- name: Define Aretha config values
  ansible.builtin.set_fact:
    aretha_repo: "{{ ansible_user_dir }}/Downloads/Aretha-Plasma-Themes"
    icons_dest: "{{ ansible_user_dir }}/.local/share/icons"
    themes_dest: "{{ ansible_user_dir }}/.local/share/themes"
    colors_dest: "{{ ansible_user_dir }}/.local/share/color-schemes"
    konsole_dest: "{{ ansible_user_dir }}/.local/share/konsole"
    kvantum_dest: "{{ ansible_user_dir }}/.config/Kvantum"
    wallpapers_dest: "{{ ansible_user_dir }}/.local/share/wallpapers"
    aretha_plasma_theme: Aretha-Dark-Plasma
    aretha_color_scheme: Aretha-Dark
    aretha_icon_theme: Aretha-Dark-Icons
    aretha_kvantum_theme: Aretha-Dark
    aretha_window_decoration: Aretha-Dark-Aurorae-6
    aretha_splashscreen: Aretha-Splash-6
    aretha_sddm_theme: Aretha-SDDM-6
    aretha_konsole_profile: Aretha-Dark.profile

- name: Clone Aretha Plasma themes
  ansible.builtin.git:
    repo: https://github.com/L4ki/Aretha-Plasma-Themes.git
    dest: "{{ aretha_repo }}"
    depth: 1
    update: true

- name: Install Aretha-Dark Plasma theme
  ansible.builtin.command:
    argv:
      - kpackagetool6
      - --type=Plasma/Theme
      - -i
      - "{{ aretha_repo }}/Aretha Plasma Themes/Aretha-Dark-Plasma"
  args:
    creates: "{{ ansible_user_dir }}/.local/share/plasma/desktoptheme/Aretha-Dark-Plasma/metadata.desktop"
  notify: reload_plasma

- name: Copy Aretha assets
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: preserve
  loop:
    - { src: "{{ aretha_repo }}/Aretha Color Schemes/",                    dest: "{{ colors_dest }}/" }
    - { src: "{{ aretha_repo }}/Aretha Konsole Color Schemes/",            dest: "{{ konsole_dest }}/" }
    - { src: "{{ aretha_repo }}/Aretha Kvantum Themes/",                   dest: "{{ kvantum_dest }}/" }
    - { src: "{{ aretha_repo }}/Aretha GTK Themes/",                       dest: "{{ themes_dest }}/Aretha-GTK/" }
    - { src: "{{ aretha_repo }}/Aretha Icons Themes/Aretha-Dark-Icons/",   dest: "{{ icons_dest }}/Aretha-Dark-Icons/" }
    - { src: "{{ aretha_repo }}/Aretha Wallpapers/",                       dest: "{{ wallpapers_dest }}/Aretha/" }
  notify: reload_plasma

- name: Install splashscreen
  ansible.builtin.command:
    argv: ["kpackagetool6", "-i", "{{ aretha_repo }}/Aretha Splashscreen/Aretha-Splash-6" ]
  args:
    creates: "{{ ansible_user_dir }}/.local/share/kpackage/generic/Aretha-Splash-6/metadata.json"

- name: Install window decorations
  ansible.builtin.command:
    argv: ["kpackagetool6", "-i", "{{ item }}" ]
  loop:
    - "{{ aretha_repo }}/Aretha Windows Decorations/Aretha-Dark-Aurorae-6"
    - "{{ aretha_repo }}/Aretha Windows Decorations/Aretha-Dark-Blur-Aurorae-6"
  args:
    creates: "{{ ansible_user_dir }}/.local/share/kpackage/generic/{{ item | basename }}/metadata.json"
  notify: reload_kwin

- name: Install SDDM theme
  ansible.builtin.copy:
    src: "{{ aretha_repo }}/Aretha SDDM Themes/Aretha-SDDM-6"
    dest: /usr/share/sddm/themes/Aretha-SDDM-6/
    remote_src: yes
    mode: '0755'
  become: true
  notify: restart_sddm

- name: Plasma desktop theme
  community.general.kdeconfig:
    path: "{{ lookup('env','XDG_CONFIG_HOME') | default(ansible_user_dir + '/.config', true) }}/plasmarc"
    values: [{ group: Theme, key: name, value: "{{ aretha_plasma_theme }}" }]
  notify: reload_plasma

- name: Global colour scheme
  community.general.kdeconfig:
    path: "{{ lookup('env','XDG_CONFIG_HOME') | default(ansible_user_dir + '/.config', true) }}/kdeglobals"
    values: [{ group: General, key: ColorScheme, value: "{{ aretha_color_scheme }}" }]
  notify: reload_plasma

- name: Icon theme
  community.general.kdeconfig:
    path: "{{ lookup('env','XDG_CONFIG_HOME') | default(ansible_user_dir + '/.config', true) }}/kdeglobals"
    values: [{ group: Icons, key: Theme, value: "{{ aretha_icon_theme }}" }]
  notify: reload_plasma

- name: Window decoration
  community.general.kdeconfig:
    path: "{{ lookup('env','XDG_CONFIG_HOME') | default(ansible_user_dir + '/.config', true) }}/kwinrc"
    values: [{ group: org.kde.kdecoration2, key: theme, value: "{{ aretha_window_decoration }}" }]
  notify: reload_kwin

- name: Kvantum theme
  community.general.kdeconfig:
    path: "{{ ansible_user_dir }}/.config/Kvantum/kvantum.kvconfig"
    values: [{ group: General, key: theme, value: "{{ aretha_kvantum_theme }}" }]
  notify: reload_plasma

- name: SDDM theme
  community.general.kdeconfig:
    path: /etc/sddm.conf.d/10-theme.conf
    values: [{ group: Theme, key: Current, value: "{{ aretha_sddm_theme }}" }]
  become: true
  notify: restart_sddm
