- name: Update all packages to latest
  ansible.builtin.package:
    name: "*"
    state: latest
    update_cache: yes
  become: true

- name: Install common packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - python3
    - python3-pip
    - tmux
    - tmate
    - htop
    - flatpak
    - curl
    - wget
    - git
    - jq
    - yq
    - rsync
    - vim
    - nano
  become: true

- name: Install packages (Fedora/RHEL)
  when: ansible_facts['os_family'] == 'RedHat'
  block:
    - name: Install common packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "@Development Tools"
        - dnf-plugins-core
        - "golang"
        - "nmap-ncat"
        - "net-tools"
      become: true

- name: Install packages (Debian/Ubuntu)
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Install common packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - "golang-go"
        - "netcat-openbsd"
        - "net-tools"
      become: true

- name: Change default shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  become: true

- name: Include oh-my-zsh tasks
  ansible.builtin.include_tasks: oh-my-zsh.yml

- name: Include 1Password Installation tasks
  ansible.builtin.include_tasks: 1password.yml

- name: Include Visual Studio Code Installation tasks
  ansible.builtin.include_tasks: vs-code.yml

- name: Include Flatpak Installation tasks
  ansible.builtin.include_tasks: flatpak.yml

- name: Include dnf productivity apps
  ansible.builtin.include_tasks: productivity-apps.yml
  when: not immutable and ansible_facts["os_family"] == 'RedHat'

