- name: Update all packages to latest
  ansible.builtin.package:
    name: "*"
    state: latest
    update_cache: yes
  become: true

- name: Install common packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - python3
    - python3-pip
    - tmux
    - tmate
    - htop
    - flatpak
    - curl
    - wget
    - git
    - jq
    - yq
    - rsync
  become: true

- name: Install packages (Fedora/RHEL)
  when: ansible_facts['os_family'] == 'RedHat'
  block:
    - name: Install common packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "@Development Tools"
        - "golang"
        - "nmap-ncat"
        - "net-tools"
        - "1password-cli"
      become: true

- name: Install packages (Debian/Ubuntu)
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Install common packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - "golang-go"
        - "netcat-openbsd"
        - "net-tools"
      become: true
