---
# NOTE: This application requires secrets for NextDNS and Proxmox widgets.
# Currently the credentials are templated via Ansible variables:
#   - homepage_nextdns_api_token
#   - proxmox_api_password
# And it requires an ArgoCD token managed by the argocd_homepage_token role.
# TODO: Migrate to OnePassword CRDs before enabling this application.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: coachlight-k3s-infra
  source:
    repoURL: https://jameswynn.github.io/helm-charts
    chart: homepage
    targetRevision: 2.1.0
    helm:
      valuesObject:
        service:
          main:
            ports:
              http:
                port: 80
                targetPort: 3000

        config:
          services:
            - Monitoring:
                - NextDNS:
                    href: https://my.nextdns.io
                    widget:
                      type: nextdns
                      profile: 62778c
                      key: ""  # TODO: Configure via OnePassword

                - Proxmox:
                    href: https://192.168.226.90:8006
                    widget:
                      type: proxmox
                      url: https://192.168.226.90:8006
                      username: sfroeber
                      password: ""  # TODO: Configure via OnePassword

          widgets:
            - datetime:
                format:
                  dateStyle: short
                  timeStyle: short
                  hourCycle: h23

            - kubernetes:
                cluster:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
                  label: "cluster"
                nodes:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true


          kubernetes:
            mode: cluster

          settings: {}

        serviceAccount:
          create: true
          name: homepage

        enableRbac: true

        ingress:
          main:
            enabled: false

        env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: "homepage.rohu-shark.ts.net"
          - name: HOMEPAGE_VAR_ARGOCD_TOKEN
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: argocdToken
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
