---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: coachlight-k3s-observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.28.0"
    helm:
      valuesObject:
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false

          commonConfig:
            replication_factor: 1

          limits_config:
            retention_period: 168h

          storage:
            type: filesystem

          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

        singleBinary:
          replicas: 1

          persistence:
            enabled: true
            storageClass: local-path-retain
            size: 10Gi

        gateway:
          enabled: false

        backend:
          replicas: 0

        read:
          replicas: 0

        write:
          replicas: 0

  destination:
    server: https://kubernetes.default.svc
    namespace: observability-loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
