---
# NOTE: This NetBox deployment currently requires secrets to be managed
# outside of this manifest. The netbox_deploy Ansible role can be used
# to template credentials until OnePassword integration is completed.
# TODO: Migrate to OnePassword CRDs or Helm chart's existingSecret support
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: coachlight-k3s-infra
  source:
    repoURL: https://netbox-community.github.io/netbox-chart
    chart: netbox
    targetRevision: "5.0.0-beta.145"
    helm:
      valuesObject:
        superuser:
          email: "admin@netbox.local"
          # TODO: Configure superuser.password field
          # Options: existingSecret, OnePassword CRD, or templated value

        # TODO: Configure secretKey field (Django secret key)
        # Options: existingSecret, OnePassword CRD, or templated value

        persistence:
          enabled: true
          storageClass: "nfs-synology-retain"

        # Use existing PostgreSQL instance
        postgresql:
          enabled: false

        # Use existing Redis instance
        redis:
          enabled: false

        # External database configuration
        externalDatabase:
          host: postgres-postgresql.db-postgres.svc.cluster.local
          port: 5432
          database: netbox
          username: netbox
          existingSecretName: netbox-db-credentials
          existingSecretKey: password

        # External Redis configuration
        externalRedis:
          host: redis-master.db-redis.svc.cluster.local
          port: 6379
          existingSecretName: netbox-redis-credentials
          existingSecretKey: password

        service:
          type: ClusterIP
          annotations:
            tailscale.com/expose: "true"
            tailscale.com/hostname: "netbox"
            tailscale.com/tags: "tag:k8s,tag:infra-monitoring"

        ingress:
          enabled: true
          className: ""
          annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: "NetBox"
            gethomepage.dev/description: "Infrastructure Resource Modeling"
            gethomepage.dev/group: "Infrastructure"
            gethomepage.dev/icon: "netbox.png"
          hosts:
            - host: netbox
              paths:
                - path: /
                  pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: infra-netbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
