---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hetzner-minio-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: hetzner-observability
  source:
    repoURL: https://github.com/SRF-Audio/utility-scripts
    targetRevision: main
    path: hetzner/k8s/minio_secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
