- name: Update all packages to the latest version
  ansible.builtin.package:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: Install
  ansible.builtin.dnf:
    name:
      - "Development Tools"
      - zsh
      - python
      - go
      - python-pip
      - 1password-cli
      - flatpak
    state: present
  become: yes

- name: Change default shell to zsh
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  become: true
