---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-primitives
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: coachlight-k3s-infra
  source:
    repoURL: https://github.com/SRF-Audio/utility-scripts
    targetRevision: main
    path: k8s/cluster_primitives
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
