hetzner_provision_artifacts:
    firewall_name: hetzner-node-fw
    server_ip: 178.104.100.13
    server_name: hetzner-node
    ssh_key_name: hetzner-bootstrap
    ssh_private_key_file: ~/.ssh/coachlight-homelab.pem
    timestamp: '2026-04-11T14:49:22Z'
    volume_id: 105381294
    volume_name: hetzner-node-vol
