apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: coachlight-k3s-db
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 23.1.1
    helm:
      valuesObject:
        image:
          repository: bitnamilegacy/redis
        auth:
          enabled: true
          existingSecret: paperless-ngx-redis-secrets
          existingSecretPasswordKey: redis-password
        master:
          podSecurityContext:
            enabled: true
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
          containerSecurityContext:
            enabled: true
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
          persistence:
            storageClass: nfs-synology-retain

        replica:
          podSecurityContext:
            enabled: true
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
          containerSecurityContext:
            enabled: true
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
          persistence:
            storageClass: nfs-synology-retain

        volumePermissions:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: db-redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
