apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: coachlight-k3s-db
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.1.1
    helm:
      valuesObject:
        image:
          repository: bitnamilegacy/postgresql

        auth:
          enablePostgresUser: false
          username: paperless
          database: paperless
          existingSecret: paperless-ngx-secrets
          secretKeys:
            userPasswordKey: PAPERLESS_DBPASS

        primary:
          replicaCount: 0
          podSecurityContext:
            enabled: true
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
          containerSecurityContext:
            enabled: true
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
          persistentVolumeClaimRetentionPolicy:
            enabled: true
            whenScaled: Retain
            whenDeleted: Retain

        volumePermissions:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: db-postgres
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
