apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: coachlight-k3s-db
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.1.1
    helm:
      valuesObject:
        image:
          repository: bitnamilegacy/postgresql
        master:
          podSecurityContext:
            enabled: true
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
          containerSecurityContext:
            enabled: true
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true

        replica:
          podSecurityContext:
            enabled: true
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
          containerSecurityContext:
            enabled: true
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true

        volumePermissions:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: db-postgres
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
