apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: coachlight-k3s-db
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgres
    targetRevision: 18.1.10
    helm:
      valuesObject:
        image:
          repository: bitnamilegacy/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: db-postgres
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
