---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: coachlight-k3s-apps
  source:
    repoURL: https://blakeblackshear.github.io/blakeshome-charts/
    chart: frigate
    targetRevision: "7.8.0"
    helm:
      valuesObject:
        config: |
          mqtt:
            enabled: false

          cameras:
            amcrest_basement_entrance:
              enabled: true
              ffmpeg:
                inputs:
                  - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.231.2:554/cam/realmonitor?channel=1&subtype=1
                    roles:
                      - detect
                  - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.231.2:554/cam/realmonitor?channel=1&subtype=0
                    roles:
                      - record

        service:
          type: ClusterIP

        persistence:
          config:
            enabled: true
            storageClass: "nfs-synology-retain"
          media:
            enabled: true
            storageClass: "nfs-synology-retain"

        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: apps-frigate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
