---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: coachlight-k3s-apps
  source:
    repoURL: https://github.com/SRF-Audio/utility-scripts
    targetRevision: main
    path: k8s/frigate_secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-frigate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
