---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: coachlight-k3s-apps
  source:
    repoURL: https://blakeblackshear.github.io/blakeshome-charts/
    chart: frigate
    targetRevision: "7.8.0"
    helm:
      valuesObject:
        config: |
          mqtt:
            enabled: false

          cameras:
            amcrest_left:
              enabled: false
              ffmpeg:
                inputs:
                  - path: rtsp://USERNAME:PASSWORD@CAMERA_IP:554/cam/realmonitor?channel=1&subtype=0
                    roles:
                      - detect
                      - record
              detect:
                enabled: false
                width: 2688
                height: 1520
                fps: 25

            amcrest_right:
              enabled: false
              ffmpeg:
                inputs:
                  - path: rtsp://USERNAME:PASSWORD@CAMERA_IP:554/cam/realmonitor?channel=2&subtype=0
                    roles:
                      - detect
                      - record
              detect:
                enabled: false
                width: 2688
                height: 1520
                fps: 25

        service:
          type: ClusterIP
          annotations:
            tailscale.com/expose: "true"
            tailscale.com/tags: "tag:k8s,tag:server-apps"
            tailscale.com/hostname: "frigate"

        persistence:
          config:
            enabled: true
            storageClass: "nfs-synology-retain"
          media:
            enabled: true
            storageClass: "nfs-synology-retain"

        ingress:
          enabled: true
          className: ""
          annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: "Frigate"
            gethomepage.dev/description: "NVR with realtime object detection"
            gethomepage.dev/group: "Cameras"
            gethomepage.dev/icon: "frigate.png"
          hosts:
            - host: frigate
              paths:
                - path: /
                  pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: apps-frigate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
