---
# Grafana admin credentials. Fields: username, password
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-admin-credentials
  namespace: observability-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/managed-by: argocd
spec:
  itemPath: "vaults/HomeLab/items/Grafana"
