---
# Generate VM configuration for workers
- name: Generate worker VM configuration list
  ansible.builtin.set_fact:
    proxmox_k3s_worker_vm_list:
      - type: worker
        specs: "{{ proxmox_k3s_worker_config.worker }}"
        count: "{{ proxmox_k3s_worker_config.worker.count }}"
        node_index: 1
        mac_suffix: "{{ (proxmox_k3s_control_plane_count | int) + 1 }}"
        ip_offset: "{{ (proxmox_k3s_control_plane_count | int) + 1 }}"
        startup_order: "{{ (proxmox_k3s_control_plane_count | int) + 1 }}"
        name: k3s-worker-1
      - type: worker
        specs: "{{ proxmox_k3s_worker_config.worker }}"
        count: "{{ proxmox_k3s_worker_config.worker.count }}"
        node_index: 2
        mac_suffix: "{{ (proxmox_k3s_control_plane_count | int) + 2 }}"
        ip_offset: "{{ (proxmox_k3s_control_plane_count | int) + 2 }}"
        startup_order: "{{ (proxmox_k3s_control_plane_count | int) + 2 }}"
        name: k3s-worker-2
      - type: media_worker
        specs: "{{ proxmox_k3s_worker_config.media_worker }}"
        count: "{{ proxmox_k3s_worker_config.media_worker.count }}"
        node_index: 3
        mac_suffix: "{{ (proxmox_k3s_control_plane_count | int) + 3 }}"
        ip_offset: "{{ (proxmox_k3s_control_plane_count | int) + 3 }}"
        startup_order: "{{ (proxmox_k3s_control_plane_count | int) + 3 }}"
        name: k3s-media-worker-1

- name: Generate complete VM list for status checking
  ansible.builtin.set_fact:
    proxmox_k3s_vm_list: "{{ control_plane_vms + worker_vms }}"
  vars:
    control_plane_vms: "{{ range(1, (proxmox_k3s_control_plane_count | int) + 1) | map('format', 'k3s-cp-%d') | list }}"
    worker_vms: "{{ proxmox_k3s_worker_vm_list | map(attribute='name') | list }}"
