- name: Query existing PVE groups
  ansible.builtin.command: pveum group list --noheader
  register: _pve_groups
  changed_when: false
  run_once: true
  when: inventory_hostname in groups['proxmox_primary']

- name: Create administrators group if missing
  ansible.builtin.command:
    argv:
      - pveum
      - group
      - add
      - "{{ pve_admin_group }}"
      - --comment
      - "{{ comment }}"
  when: (_pve_groups.stdout is defined and pve_admin_group not in _pve_groups.stdout) and inventory_hostname in groups['proxmox_primary']

- name: Ensure administrators group has the Administrator role at /
  ansible.builtin.command:
    argv:
      - pveum
      - acl
      - modify
      - /
      - --groups
      - "{{ pve_admin_group }}"
      - --role
      - Administrator
  register: _acl_change
  changed_when: "'(group {{ pve_admin_group }})' in _acl_change.stderr"
  when: inventory_hostname in groups['proxmox_primary']

- name: Query existing PVE users
  ansible.builtin.command: pveum user list --noheader
  register: _pve_users
  changed_when: false
  run_once: true
  when: inventory_hostname in groups['proxmox_primary']

- name: Add sfroeber to PVE
  ansible.builtin.command:
    argv:
      - pveum
      - user
      - add
      - "{{ pve_admin_user }}"
      - --comment
      - "{{ comment }}"
  when: pve_admin_user not in _pve_users.stdout and inventory_hostname in groups['proxmox_primary']
  register: _user_add

- name: Add sfroeber to administrators group
  ansible.builtin.command:
    argv:
      - pveum
      - user
      - modify
      - "{{ pve_admin_user }}"
      - --groups
      - "{{ pve_admin_group }}"
  when: (_user_add is defined and _user_add.changed or pve_admin_user not in _pve_users.stdout) and inventory_hostname in groups['proxmox_primary']

- name: Explain password steps
  ansible.builtin.debug:
    msg: |
      Password for {{ pve_admin_user }} cannot be set programmatically.
      Log into the node with `ssh root@coachlight-homelab-1` and run:
      ```
      pveum passwd {{ pve_admin_user }}@pam
      ```

- name: Query existing pools
  ansible.builtin.command: pveum pool list --noheader
  register: _pools
  changed_when: false
  when: inventory_hostname in groups['proxmox_primary']

- name: Create kubernetes pool
  ansible.builtin.command:
    argv:
      - pveum
      - pool
      - add
      - kubernetes
      - --comment
      - "All Kubernetes VMs/CTs"
  when: (inventory_hostname in groups['proxmox_primary']) and (_pools.stdout is defined and 'kubernetes' not in _pools.stdout)
