---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox-db-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: coachlight-k3s-db
  source:
    repoURL: https://github.com/SRF-Audio/utility-scripts
    targetRevision: main
    path: k8s/db-provisioning/netbox
  destination:
    server: https://kubernetes.default.svc
    namespace: db-postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
