---
# This OnePasswordItem creates a Secret named "frigate-mqtt-credentials" in the
# apps-frigate namespace. The 1Password item must have the following fields:
# - FRIGATE_MQTT_USER
# - FRIGATE_MQTT_PASSWORD
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: frigate-mqtt-credentials
  namespace: apps-frigate
spec:
  itemPath: "vaults/HomeLab/items/frigate-mqtt-credentials"
