---
- name: Setup K3s HA Cluster on Proxmox
  hosts: proxmox_primary
  gather_facts: true
  vars:
    pve_admin_user: "{{ lookup('community.general.onepassword', 'Coachlight ProxMox Cluster', field='username', vault='HomeLab') | default('root@pam') }}"
    pve_admin_password: "{{ lookup('community.general.onepassword', 'Coachlight ProxMox Cluster', field='password', vault='HomeLab') }}"
    proxmox_node_name: "{{ inventory_hostname }}"
  roles:
    - role: proxmox

- name: Wait for cluster to be ready
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for control plane nodes to be accessible
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 22
        delay: 10
        timeout: 300
      loop:
        - "{{ proxmox_k3s_control_plane_start_ip }}"
        - "{{ proxmox_k3s_control_plane_start_ip | ipaddr('+1') }}"
        - "{{ proxmox_k3s_control_plane_start_ip | ipaddr('+2') }}"

    - name: Wait for worker nodes to be accessible
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 22
        delay: 10
        timeout: 300
      loop:
        - "{{ proxmox_k3s_control_plane_start_ip | ipaddr('+3') }}"
        - "{{ proxmox_k3s_control_plane_start_ip | ipaddr('+4') }}"
        - "{{ proxmox_k3s_control_plane_start_ip | ipaddr('+5') }}"

- name: Verify K3s cluster status
  hosts: "{{ proxmox_k3s_control_plane_start_ip }}"
  gather_facts: false
  tasks:
    - name: Check K3s cluster status
      ansible.builtin.command: kubectl get nodes
      register: cluster_status
      retries: 10
      delay: 30
      until: cluster_status.rc == 0
      changed_when: false

    - name: Display cluster status
      ansible.builtin.debug:
        var: cluster_status.stdout_lines
