---
# Requires 1Password Operator to be installed and configured
# The operator will create a Kubernetes Secret named 'minio-credentials'
# with keys matching the field names in the 1Password item
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: minio-credentials
  namespace: observability-minio
spec:
  itemPath: "vaults/HomeLab/items/k3s-observability-minio"
