{{- if not .Values.app.session.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leantime.sessionSecretName" . }}
  labels:
    {{- include "leantime.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "leantime.sessionSecretKey" . }}: {{ required "app.session.password is required when app.session.existingSecret.name is empty" .Values.app.session.password | b64enc }}
{{- end }}
