- name: Install productivity packages
  ansible.builtin.dnf:
    name:
      - inkscape
      - steam
      - musescore
      - krita
      - libreoffice
      - kdenlive
      - tailscale
      - coreos-installer
    state: present
  become: true
