---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - onepassword-postgres.yml
  - onepassword-postgres-admin.yml
  - onepassword-netbox-db.yml
  - postgres-provision-job.yml
  # - postgres-pv-migration-job.yml
