---
hetzner_provision_server_name: hetzner-node
hetzner_provision_server_type: cax31
hetzner_provision_image: fedora-41
hetzner_provision_location: nbg1
hetzner_provision_firewall_name: hetzner-node-fw
hetzner_provision_volume_name: hetzner-node-vol
hetzner_provision_volume_size_gb: 500
hetzner_provision_ssh_private_key_file: ~/.ssh/coachlight-homelab.pem
hetzner_provision_artifacts_path: "{{ artifacts_path | default(playbook_dir ~ '/.artifacts') }}"
