- name: Stephen's Fedora Setup Playbook
  hosts: localhost
  gather_facts: yes
  vars_prompt:
    - name: install_devtools
      prompt: "Do you want to install extra developer tools? (y/n)"
      private: no
  
  vars:
    ansible_user: sfroeber
  tasks:
    - name: Update all packages to the latest version
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      become: yes

    - name: Install git
      dnf:
        name: git
        state: present
      become: yes
    
    - name: Install Development Tools group
      dnf:
        name: "@Development Tools"
        state: present
      become: yes

    - name: Install zsh
      dnf:
        name: zsh
        state: present
      become: yes

    - name: Change default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh

    - name: Check if oh-my-zsh is installed
      stat:
        path: ~/.oh-my-zsh
      register: ohmyzsh_stat

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
      args:
        executable: /bin/sh
      when: not ohmyzsh_stat.stat.exists

    - name: Set ZSH_THEME to "agnoster" in .zshrc
      lineinfile:
        path: ~/.zshrc
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME="agnoster"'

    - name: Import 1Password GPG key
      rpm_key:
        state: present
        key: https://downloads.1password.com/linux/keys/1password.asc

    - name: Add 1Password repository
      yum_repository:
        name: 1password
        description: 1Password Stable Channel
        baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc

    - name: Install 1Password
      dnf:
        name: 1password
        state: present
      become: yes

    - name: Import Microsoft GPG key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Visual Studio Code repository
      yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: yes
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Install VS Code
      dnf:
        name: code
        state: present
      become: yes

    - name: Install dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: present
      become: yes

    - name: Install TigerVNC
      dnf:
        name: tigervnc
        state: present
      become: yes

    - name: Install flatpak
      dnf:
        name: flatpak
        state: present
      become: yes

    - name: Add Fedora Flatpak remote
      command: flatpak remote-add --if-not-exists fedora oci+https://registry.fedoraproject.org

    - name: Add Flathub Flatpak remote
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Obsidian via Flatpak
      command: flatpak install -y flathub md.obsidian.Obsidian

    - name: Install Slack via Flatpak
      command: flatpak install -y flathub com.slack.Slack

    

    # # KDE Settings
    # - name: Set KDE color scheme
    #   shell: kwriteconfig5 --file kdeglobals --group General --key ColorScheme --value "ColorfulVioletDarkColorscheme"
    #   become_user: "{{ ansible_user }}"

    # - name: Set KDE icon theme
    #   shell: kwriteconfig5 --file kdeglobals --group Icons --key Theme --value "BeautySolar"
    #   become_user: "{{ ansible_user }}"

    # - name: Apply changes
    #   shell: kbuildsycoca5 --noincremental
    #   become_user: "{{ ansible_user }}"

    # - name: Ensure the .config directory exists
    #   file:
    #     path: "{{ user_home }}/.config"
    #     state: directory
    #     owner: "{{ ansible_user }}"
    #     group: "{{ ansible_user }}"
    #     mode: '0755'
    #   become_user: "{{ ansible_user }}"  

    # - name: Copy KDE plasma desktop configuration file
    #   copy:
    #     src: "./files/plasma-org.kde.plasma.desktop-appletsrc"
    #     dest: "{{ user_home }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    #     owner: "{{ ansible_user }}"
    #     group: "{{ ansible_user }}"
    #     mode: '0644'
    #   become_user: "{{ ansible_user }}"  # Run as the user who will use KDE

    # - name: Restart KDE Plasma to apply configuration
    #   shell: kquitapp5 plasmashell && kstart5 plasmashell
    #   become_user: "{{ ansible_user }}"
    #   async: 10
    #   poll: 0

    - block:
        - name: Install Docker dependencies
          dnf:
            name: dnf-plugins-core
            state: present

        - name: Add Docker CE repository
          get_url:
            url: https://download.docker.com/linux/fedora/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
            mode: '0644'

        - name: Install Docker packages
          dnf:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present

        - name: Start and enable Docker service
          systemd:
            name: docker
            state: started
            enabled: yes

        - name: Add user to docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

        - name: Check if running in a VM
          set_fact:
            is_vm: "{{ ansible_facts.virtualization_role == 'guest' }}"

        - block:
            - name: Download Docker Desktop RPM
              get_url:
                url: https://desktop.docker.com/linux/main/amd64/docker-desktop-4.25.1-x86_64.rpm
                dest: /tmp/docker-desktop.rpm

            - name: Install Docker Desktop
              dnf:
                name: /tmp/docker-desktop.rpm
                state: present

            - name: Remove Docker Desktop RPM file
              file:
                path: /tmp/docker-desktop.rpm
                state: absent
          when: not is_vm

        - name: Create fonts directory
          file:
            path: ~/.local/share/fonts
            state: directory
            mode: '0755'

        - name: Download FiraMono Nerd Font
          get_url:
            url: https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/FiraMono/Regular/FiraMonoNerdFontMono-Regular.otf
            dest: ~/.local/share/fonts/FiraMonoNerdFontMono-Regular.otf

        - name: Install additional developer tools
          dnf:
            name:
              - jq
              - nmap
              - htop
            state: present

        - name: Install packages via Homebrew
          loop:
            - python
            - go
            - kind
            - kubectl
            - helm
            - kustomize
            - skaffold
            - istioctl
            - derailed/k9s/k9s
            - fx
            - yh
          command: /home/linuxbrew/.linuxbrew/bin/brew install {{ item }}

        - name: Add alias for python3 in .bashrc
          lineinfile:
            path: ~/.bashrc
            line: "alias python='python3'"
            insertafter: EOF

        - name: Add alias for python3 in .zshrc
          lineinfile:
            path: ~/.zshrc
            line: "alias python='python3'"
            insertafter: EOF

        - name: Upgrade pip for Python 3
          shell: python3 -m ensurepip --upgrade

        - name: Add alias for pip3 in .bashrc
          lineinfile:
            path: ~/.bashrc
            line: "alias pip='pip3'"
            insertafter: EOF

        - name: Add alias for pip3 in .zshrc
          lineinfile:
            path: ~/.zshrc
            line: "alias pip='pip3'"
            insertafter: EOF
      when: install_devtools == "y"

    - name: Get PCI devices
      command: lspci
      register: lspci_output

    - name: Check for NVIDIA graphics card
      set_fact:
        has_nvidia: "{{ 'nvidia' in lspci_output.stdout.lower() }}"

    - block:
        - name: Set Fedora version
          set_fact:
            fedora_version: "{{ ansible_distribution_version | int }}"

        - name: Install RPM Fusion free repository
          dnf:
            name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
            state: present

        - name: Install RPM Fusion nonfree repository
          dnf:
            name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
            state: present

        - name: Update DNF repositories
          dnf:
            name: "*"
            state: latest
            update_cache: yes

        - name: Install DaVinci Resolve dependencies
          dnf:
            name:
              - apr
              - apr-util
              - mesa-libGLU
            state: present

        - name: Remove existing NVIDIA packages if any
          dnf:
            name: "*nvidia*"
            state: absent
            autoremove: yes

        - name: Install NVIDIA drivers
          dnf:
            name:
              - akmod-nvidia
              - xorg-x11-drv-nvidia
              - xorg-x11-drv-nvidia-libs.i686
              - xorg-x11-drv-nvidia-cuda
            state: present

        - name: Blacklist nouveau driver
          lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            line: 'blacklist nouveau'
            create: yes

        - name: Rebuild initramfs
          command: dracut --force

        - name: Update kernel
          dnf:
            name: kernel
            state: latest

        - name: Check Secure Boot status
          command: mokutil --sb-state
          register: sb_state
          failed_when: false

        - name: Notify about Secure Boot if enabled
          debug:
            msg: "Secure Boot is enabled. You'll need to disable it to finish NVIDIA drivers installation properly."
          when: "'enabled' in sb_state.stdout.lower()"

        - name: Notify that NVIDIA drivers are installed
          debug:
            msg: "NVIDIA drivers installed successfully."
          when: "'enabled' not in sb_state.stdout.lower()"
      when: has_nvidia

    - name: Reboot the system
      reboot:
