---
- name: Test IP Calculation
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_k3s_control_plane_start_ip: "192.168.226.93"
  tasks:
    - name: Calculate IPs for additional control plane nodes
      ansible.builtin.set_fact:
        node_ips: "{{ node_ips | default([]) + [proxmox_k3s_control_plane_start_ip.split('.')[:-1] | join('.') + '.' + ((proxmox_k3s_control_plane_start_ip.split('.')[-1] | int) + (item | int - 1) | string)] }}"
      loop: "{{ range(2, 4) | list }}"

    - name: Display calculated IPs
      ansible.builtin.debug:
        msg: "Node {{ index + 2 }} IP: {{ item }}"
      loop: "{{ node_ips }}"
      loop_control:
        index_var: index

    - name: Calculate IPs for worker nodes
      ansible.builtin.set_fact:
        worker_ips: "{{ worker_ips | default([]) + [proxmox_k3s_control_plane_start_ip.split('.')[:-1] | join('.') + '.' + ((proxmox_k3s_control_plane_start_ip.split('.')[-1] | int) + (item.ip_offset | int) | string)] }}"
      vars:
        proxmox_k3s_worker_vm_list:
          - name: "k3s-worker-1"
            ip_offset: 5
          - name: "k3s-worker-2"
            ip_offset: 6
      loop: "{{ proxmox_k3s_worker_vm_list }}"

    - name: Display worker IPs
      ansible.builtin.debug:
        msg: "Worker {{ item.name }} IP: {{ worker_ips[loop.index0] }}"
      loop: "{{ proxmox_k3s_worker_vm_list }}"
