---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-ngx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: coachlight-k3s-apps
  source:
    repoURL: https://github.com/SRF-Audio/utility-scripts
    targetRevision: main
    path: k8s/paperless_ngx
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-paperless-ngx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
