---
# NOTE: This application uses Tailscale OAuth credentials stored in 1Password.
# The credentials are synced via the OnePasswordItem CRD in wave 10.
# A transformation job creates the 'operator-oauth' secret with the correct key names.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: coachlight-k3s-infra
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "1.90.8"
    helm:
      valuesObject:
        oauth: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tailscale-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
