---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: coachlight-k3s-infra
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "1.90.8"
    helm:
      valuesObject:
        oauthSecretVolume:
          secret:
            secretName: tailscale-operator-oauth
            items:
              - key: tailscale_oauth_client_id
                path: client_id
              - key: tailscale_oauth_client_secret
                path: client_secret
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tailscale-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
