---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: observability-minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: console
    app.kubernetes.io/managed-by: argocd
  annotations:
    tailscale.com/tags: "tag:k8s,tag:server-apps"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "MinIO"
    gethomepage.dev/description: "S3-compatible object storage"
    gethomepage.dev/group: "Observability"
    gethomepage.dev/icon: "minio.png"
    gethomepage.dev/pod-selector: "app=minio,release=hetzner-minio"
    gethomepage.dev/href: "https://minio-hetzner.rohu-shark.ts.net"
    gethomepage.dev/url: "http://hetzner-minio-console.observability-minio.svc.cluster.local:9001"
    gethomepage.dev/siteMonitor: "http://hetzner-minio-console.observability-minio.svc.cluster.local:9001"
spec:
  ingressClassName: tailscale
  rules:
    - host: minio-hetzner.rohu-shark.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hetzner-minio-console
                port:
                  number: 9001
  tls:
    - hosts:
        - minio-hetzner.rohu-shark.ts.net
